var pricing_one_col = '[respo_pricing plan_id="" per="per month" button_text="Sign Up" button_color="blue" color="blue" button_target="self" button_rel="nofollow"]<ul>	<li>Write Something here</li>	<li>Write Something here</li>	<li>Write Something here</li>	<li>Write Something here</li></ul>[/respo_pricing]';

var pricing_two_col = '[respo_pricing plan_id="" per="per month" button_text="Sign Up" button_color="blue" color="blue" button_target="self" button_rel="nofollow"]<ul>	<li>Write Something here</li>	<li>Write Something here</li>	<li>Write Something here</li>	<li>Write Something here</li></ul>[/respo_pricing][respo_pricing plan_id="" per="per month" button_url="#" button_text="Sign Up" button_color="blak" button_target="self" button_rel="nofollow"]<ul>	<li>15GB Bandwidth</li>	<li>350 MB Storage</li>	<li>5 Domains</li>	<li>4</li></ul>[/respo_pricing]';

var pricing_three_col = '[one_third_first][respo_pricing plan_id="" per="per month" button_text="Sign Up" button_color="blue" color="blue" button_target="self" button_rel="nofollow"]<ul>	<li>Write Something here</li>	<li>Write Something here</li> <li>Write Something here</li>	<li>Write Something here</li></ul>[/respo_pricing][/one_third_first][one_third][respo_pricing plan_id="" per="per month" button_text="Sign Up" button_color="blak" button_target="self" button_rel="nofollow"]<ul>	<li>15GB Bandwidth</li>	<li>350 MB Storage</li>	<li>5 Domains</li>	<li>4</li></ul>[/respo_pricing][/one_third][one_third_last][respo_pricing plan_id="" per="per month" button_text="Sign Up" button_color="green" color="green" button_target="self" button_rel="nofollow"]<ul>	<li>25GB Bandwidth</li>	<li>450 MB Storage</li>	<li>7 Domains</li>	<li>4</li></ul>[/respo_pricing][/one_third_last]';

var pricing_four_col = '[one_fourth_first][respo_pricing plan_id="" per="per month"  button_text="Sign Up" button_color="blue" color="blue" button_target="self" button_rel="nofollow"]<ul>	<li>text</li>	<li>text</li>	<li>text</li>	<li>text</li></ul>[/respo_pricing][/one_fourth_first][one_fourth][respo_pricing plan_id="" per="per month"  button_text="Sign Up" button_color="blak" button_target="self" button_rel="nofollow"]<ul>	<li>15GB Bandwidth</li>	<li>350 MB Storage</li>	<li>5 Domains</li>	<li>4</li></ul>[/respo_pricing][/one_fourth][one_fourth][respo_pricing plan_id="" per="per month" button_text="Sign Up" button_color="green" color="green" button_target="self" button_rel="nofollow"]<ul>	<li>25GB Bandwidth</li>	<li>450 MB Storage</li>	<li>7 Domains</li>	<li>4</li></ul>[/respo_pricing][/one_fourth][one_fourth_last][respo_pricing plan_id="" per="per month" button_text="Sign Up" button_color="yellow" color="yellow" button_target="self"button_rel="nofollow"]<ul>	<li>35GB Bandwidth</li>	<li>550 MB Storage</li>	<li>9 Domains</li>	<li>4</li></ul>[/respo_pricing][/one_fourth_last]';
var grid_two_col = '[one_half_first]This is the first column[/one_half_first][one_half_last]This is the second and last column[/one_half_last]';

var grid_three_col = '[one_third_first]This is the first column[/one_third_first][one_third]This is the second column[/one_third][one_third_last]This is the third and last column[/one_third_last]';

var grid_four_col = '[one_fourth_first]This is the first column[/one_fourth_first][one_fourth]This is the second column[/one_fourth][one_fourth]This is the third column[/one_fourth][one_fourth_last]This is the fourth and last column[/one_fourth_last]';

var grid_six_col = '[one_sixth_first]This is the first column[/one_sixth_first][one_sixth]This is the second column[/one_sixth][one_sixth]This is the third column[/one_sixth][one_sixth]This is the fourth column[/one_sixth][one_sixth]This is the fifth column[/one_sixth][one_sixth_last]This is the sixth and last column[/one_sixth_last]';